version: '3'

services:
  frontend:
    build: modules/frontend
    ports:
      - 80:80
  db:
    image: mysql/mysql-server:5.7.22
    volumes:
      - /schema:/docker-entrypoint-initdb.d
      - /data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_HOST: "localhost"
      MYSQL_ROOT_PASSWORD:  "123456"
      MYSQL_DATABASE: "annotator"
      MYSQL_USER: "annotator"
      MYSQL_PASSWORD: "123456"
      MYSQL_LOG_CONSOLE: "true"
    restart: always

  backend:
    build: modules/backend
    links:
      - db
    ports:
      - 5000:5000
    environment:
      HOST: db
      NODE_ENV: development
      PORT: 5000